#!/usr/bin/env python3
"""Guard that the thin client's method -> /v1 route map is in sync with the
server registry.

The map is generated from src/server/server_http_routes.c by
scripts/gen-cli-v1-routes.py and lives inline in the thin-client TU
(src/cli_v1_routes*.c) between the @@GEN-CLI-V1-ROUTES BEGIN/END markers. This
check regenerates the block and diffs it against what's committed in the file, so
a registry change that isn't reflected in the committed map fails `make lint`
instead of silently leaving the client without its first-class /v1 route.

Beyond that sync check, three independent directions must hold for a command to
actually work. Each has its own check, and each shipped broken at least once:

  route + marshaller, no dispatch row  -> unreachable_methods()
  dispatch row + route, no marshaller  -> dispatchable_without_marshaller()
  dispatch row, NO ROUTE               -> dispatchable_without_route()

The last one is the newest and the most severe: the thin client reaches the
server only through a first-class /v1 route now that the generic dispatch
endpoint is retired, so such a command cannot work on ANY transport.
"""
import glob
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GEN = ROOT / "scripts" / "gen-cli-v1-routes.py"
TARGET_GLOB = str(ROOT / "src" / "cli_v1_routes*.c")
MARK_BEGIN = "/* @@GEN-CLI-V1-ROUTES BEGIN — generated by scripts/gen-cli-v1-routes.py; DO NOT EDIT @@ */"
MARK_END = "/* @@GEN-CLI-V1-ROUTES END @@ */"


def committed_block():
    for f in sorted(glob.glob(TARGET_GLOB)):
        text = Path(f).read_text(encoding="utf-8")
        if MARK_BEGIN in text:
            return f, text.split(MARK_BEGIN, 1)[1].split(MARK_END, 1)[0].strip("\n")
    return None, None


def main() -> int:
    fname, committed = committed_block()
    if committed is None:
        print("check-cli-v1-routes: FAIL — @@GEN-CLI-V1-ROUTES markers not found in "
              "src/cli_v1_routes*.c; run scripts/gen-cli-v1-routes.py")
        return 1
    fresh = subprocess.run([sys.executable, str(GEN), "--stdout"],
                           check=True, capture_output=True, text=True).stdout.strip("\n")
    if committed != fresh:
        print("check-cli-v1-routes: FAIL — the generated /v1 route map is stale vs "
              "server_http_routes.c; run scripts/gen-cli-v1-routes.py and commit.")
        return 1
    n = sum(1 for ln in fresh.splitlines() if ln.lstrip().startswith('{"'))

    orphans = unreachable_methods()
    if orphans:
        print("check-cli-v1-routes: FAIL — these /v1 methods have a route and a "
              "marshaller but no `aimee <cmd> <sub>` row in the dispatch table in "
              "src/cli_v1_routes.c, so no thin client can invoke them:")
        for m in orphans:
            print(f"  {m}")
        return 1

    unmarshalled = dispatchable_without_marshaller()
    if unmarshalled:
        print("check-cli-v1-routes: FAIL — these methods have a dispatch row and a "
              "route but NO marshaller, so the command exists, is documented, and "
              "exits 2 with \"arguments are missing or invalid\" whatever you pass it. "
              "Add a {method, marshal_*} entry, or MARSHAL_NO_ARGS for a bare GET:")
        for m in unmarshalled:
            print(f"  {m}")
        return 1

    unrouted = dispatchable_without_route()
    if unrouted:
        print("check-cli-v1-routes: FAIL — these methods have an `aimee <cmd> <sub>` "
              "dispatch row but NO /v1 route, so the command is advertised in the help "
              "and cannot reach the server on ANY transport; it only ever answers "
              "\"has no /v1 route\". Add a row to g_v1_routes[] in "
              "src/server/server_http_routes.c and regenerate:")
        for m in unrouted:
            print(f"  {m}")
        return 1

    print(f"check-cli-v1-routes: ok ({n} client /v1 routes in sync, all reachable, "
          f"all marshalled, all routed)")
    return 0


# The generated block above keeps method -> /v1 path in sync with the server, but
# the CLI subcommand -> method table is hand-written, so a method could be fully
# plumbed (path + marshaller + printer) and still be unreachable from the CLI.
# That is how `aimee kb build` shipped answering "command 'kb' has no /v1 route"
# while POST /v1/kb/build worked -- every piece existed except the dispatch row.
ROUTE_RE = re.compile(r'\{"([a-z0-9_.]+)",\s*"(?:GET|POST|PUT|DELETE)",\s*"/v1/[^"]+"\}')
MARSHAL_RE = re.compile(r'\{"([a-z0-9_.]+)",\s*marshal_[a-z0-9_]+\}')
DISPATCH_RE = re.compile(r'\{"[a-z0-9_-]+",\s*(?:NULL|"[a-z0-9 _-]*")\s*,\s*"([a-z0-9_.]+)"')


# marshal_request() resolves a method through FIVE paths, and a check that knows
# about only some of them cries wolf. These mirror the function itself: exact
# strcmp cases, {method, marshal_*} tables, the MARSHAL_NO_ARGS string list, and
# strncmp prefix fallbacks. Parsed from the source so adding a path there does not
# silently narrow this check.
MARSHAL_FN_RE = re.compile(r"cJSON \*marshal_request\(.*?\n\}", re.S)
EXACT_RE = re.compile(r'strcmp\(method,\s*"([a-z0-9_.]+)"\)\s*==\s*0')
PREFIX_RE = re.compile(r'strncmp\(method,\s*"([a-z0-9_.]+)",\s*\d+\)\s*==\s*0')
NO_ARGS_RE = re.compile(r"MARSHAL_NO_ARGS\[\]\s*=\s*\{(.*?)\};", re.S)
NO_ARGS_ITEM_RE = re.compile(r'"([a-z0-9_.]+)"')


def marshal_coverage():
    """(exact methods, prefixes) that marshal_request() can build a request for."""
    exact, prefixes = set(), set()
    for f in sorted(glob.glob(TARGET_GLOB)):
        text = Path(f).read_text(encoding="utf-8")
        exact |= set(MARSHAL_RE.findall(text))          # {method, marshal_*} tables
        for block in NO_ARGS_RE.findall(text):          # plain string list
            exact |= set(NO_ARGS_ITEM_RE.findall(block))
        for body in MARSHAL_FN_RE.findall(text):        # hand-written cases
            exact |= set(EXACT_RE.findall(body))
            prefixes |= set(PREFIX_RE.findall(body))
    return exact, prefixes


def dispatchable_without_marshaller():
    """Methods the CLI offers that marshal_request() cannot build a request for.

    THE OTHER DIRECTION FROM unreachable_methods(), and the one that was missing.
    That one catches a method plumbed with no dispatch row. This catches a method WITH
    a dispatch row and a path and no marshaller at all, which is worse for a user: the
    command appears in the help, is documented, and then refuses every invocation with
    a usage error that blames their arguments.

    Three shipped exactly like that -- `aimee kb curator status`, `aimee doctor
    forensics`, `aimee economizer stats`. Route table entry, dispatch row, printer,
    the GET serving fine, and no marshaller, so each answered "arguments are missing
    or invalid, so no request was sent" whether you passed arguments or not.
    """
    routed = set()
    for f in sorted(glob.glob(TARGET_GLOB)):
        routed |= set(ROUTE_RE.findall(Path(f).read_text(encoding="utf-8")))
    dispatch = set(DISPATCH_RE.findall(
        Path(ROOT / "src" / "cli_v1_routes.c").read_text(encoding="utf-8")))
    exact, prefixes = marshal_coverage()
    # Only methods that also have a path: a dispatch row for a method with no route is
    # a different defect, reported by dispatchable_without_route(). (That was not true
    # when this comment was written -- it claimed the generated-map check above covered
    # it, which only verifies the block matches the descriptor and says nothing about
    # dispatch rows. Nothing covered it, which is how `workers` and every `pipeline`
    # subcommand shipped unroutable.)
    missing = (dispatch & routed) - exact
    return sorted(m for m in missing if not any(m.startswith(p) for p in prefixes))


def unreachable_methods():
    routed, marshalled = set(), set()
    for f in sorted(glob.glob(TARGET_GLOB)):
        text = Path(f).read_text(encoding="utf-8")
        routed |= set(ROUTE_RE.findall(text))
        marshalled |= set(MARSHAL_RE.findall(text))
    dispatch = set(DISPATCH_RE.findall(
        Path(ROOT / "src" / "cli_v1_routes.c").read_text(encoding="utf-8")))
    return sorted((routed & marshalled) - dispatch)


# THE THIRD DIRECTION. unreachable_methods() catches a routed method with no dispatch
# row; dispatchable_without_marshaller() catches a dispatch row with no marshaller.
# Neither catches a dispatch row with NO ROUTE -- and since the generic dispatch
# endpoint was retired, the thin client reaches the server ONLY through a first-class
# /v1 route, so that command cannot work on any transport. It is advertised in
# `aimee help`, documented, and answers "has no /v1 route" forever.
#
# `aimee workers` and all seven `aimee pipeline` subcommands shipped exactly like
# that: handler, capability entry, dispatch row, marshaller and printer all present,
# and no row in g_v1_routes[].
#
# rpc_routes[] rows are (cmd, subcommand, method, server_method, ...). When
# server_method is set THAT is what gets routed, not method -- `aimee memory archive`
# dispatches memory.archive but routes memory.user_capture, and `aimee git verify`
# routes mcp.call. Resolving the wrong one here would report four working commands as
# broken. Parse only the rpc_routes[] table, so unrelated brace-lists elsewhere in the
# file (bool flag names, response keys) cannot masquerade as dispatch rows.
RPC_TABLE_RE = re.compile(r"\}\s*rpc_routes\[\]\s*=\s*\{(.*?)\n\};", re.S)
RPC_ROW_RE = re.compile(
    r'\{"[a-z0-9_-]+",\s*(?:NULL|"[a-z0-9 _-]*")\s*,\s*"([a-z0-9_.]+)"\s*,'
    r'\s*(NULL|"[a-z0-9_.]+")')
# {id}-bearing routes: {method, verb, prefix, suffix, id_field} -- five fields, so a
# distinct shape from the three-field {method, verb, path} rows ROUTE_RE finds.
PATHID_RE = re.compile(
    r'\{"([a-z0-9_.]+)",\s*"(?:GET|POST|PUT|DELETE)",\s*"/v1/[^"]*",'
    r'\s*"[^"]*",\s*(?:NULL|"[^"]*")\s*\}')


def dispatchable_without_route():
    """Methods the CLI dispatches that resolve to no /v1 route at all."""
    routed = set()
    for f in sorted(glob.glob(TARGET_GLOB)):
        text = Path(f).read_text(encoding="utf-8")
        routed |= set(ROUTE_RE.findall(text))    # generated sync + async, and bespoke[]
        routed |= set(PATHID_RE.findall(text))   # {id}-bearing prefix routes
    src = Path(ROOT / "src" / "cli_v1_routes.c").read_text(encoding="utf-8")
    table = RPC_TABLE_RE.search(src)
    if not table:
        raise SystemExit("check-cli-v1-routes: rpc_routes[] table not found in "
                         "src/cli_v1_routes.c; this check cannot run")
    effective = set()
    for method, server_method in RPC_ROW_RE.findall(table.group(1)):
        effective.add(server_method.strip('"') if server_method != "NULL" else method)
    return sorted(effective - routed)


if __name__ == "__main__":
    sys.exit(main())
