/* gen-memory-ontology-seed.c: emit the seed ontology the Go memory module uses,
 * asked of the compiled C table rather than parsed out of its source.
 *
 * Parsing src/rel_types.c was tried first and silently produced a different row
 * count -- a grep was also counting the separate alias table. Walking
 * rel_types_seed_count/rel_types_seed_at is the authority. Regenerate after any
 * change to SEED_ONTOLOGY:
 *
 *   cc -std=c11 -Wall -Wextra -Isrc -Isrc/headers -o /tmp/gen-seed \
 *      scripts/gen-memory-ontology-seed.c src/rel_types.c
 *   /tmp/gen-seed server-go/modules/memory/ontology_seed.go \
 *                 server-go/modules/memory/testdata/ontology_seed.tsv
 *
 * Only the fields the module reads are carried: the kinds the write gate checks
 * and the sensitivity tier the recall gate reads. */
#include "rel_types.h"

#include <stdio.h>
#include <stdlib.h>

/* The Go NodeKind constant naming, so the generated table reads like hand-written
 * Go rather than a list of integers. Anything unnamed is a seed row referring to
 * a kind the Go port does not model, which must fail loudly, not silently emit
 * an integer that compiles. */
static const char *go_node_kind(memory_node_kind_t kind)
{
   switch (kind)
   {
   case NODE_FILE: return "NodeFile";
   case NODE_FUNCTION: return "NodeFunction";
   case NODE_STRUCT: return "NodeStruct";
   case NODE_MODULE: return "NodeModule";
   case NODE_BUG: return "NodeBug";
   case NODE_COMMIT: return "NodeCommit";
   case NODE_PR: return "NodePr";
   case NODE_DEVELOPER: return "NodeDeveloper";
   case NODE_CONCEPT: return "NodeConcept";
   case NODE_EVENT: return "NodeEvent";
   case NODE_PERSON: return "NodePerson";
   case NODE_PLACE: return "NodePlace";
   case NODE_TIME_EXPR: return "NodeTimeExpr";
   case NODE_DEVICE: return "NodeDevice";
   case NODE_ORG: return "NodeOrg";
   case NODE_IP: return "NodeIp";
   case NODE_SCALAR: return "NodeScalar";
   case NODE_OTHER: return "NodeOther";
   default: return NULL;
   }
}

static const char *go_sensitivity(rel_sensitivity_t sens)
{
   switch (sens)
   {
   case SENS_NORMAL: return "SensNormal";
   case SENS_PII: return "SensPII";
   case SENS_SECRET: return "SensSecret";
   default: return NULL;
   }
}

static void write_kind_list(FILE *f, const memory_node_kind_t *kinds, int count)
{
   fputs("[]NodeKind{", f);
   for (int i = 0; i < count; i++)
   {
      const char *name = go_node_kind(kinds[i]);
      if (!name)
      {
         fprintf(stderr, "seed row uses node kind %d, which the Go port does not name\n", kinds[i]);
         exit(1);
      }
      fprintf(f, "%s%s", i ? ", " : "", name);
   }
   fputc('}', f);
}

static void write_go(const char *path)
{
   FILE *f = fopen(path, "w");
   if (!f)
   {
      perror(path);
      exit(1);
   }
   fputs("// Code generated by scripts/gen-memory-ontology-seed.c from src/rel_types.c\n"
         "// SEED_ONTOLOGY. DO NOT EDIT BY HAND.\n"
         "// Regenerate when the C table changes; ontology_conformance_test.go compares\n"
         "// this against testdata/ontology_seed.tsv, generated in the same walk.\n"
         "\n"
         "package memory\n"
         "\n"
         "// seedOntology is the memory module's relation table: the entity kinds the\n"
         "// write gate allows at each end, and the sensitivity tier the recall gate\n"
         "// reads. NodeOther in a kind list is the ANY wildcard.\n"
         "var seedOntology = []relTypeDef{\n",
         f);
   for (int i = 0; i < rel_types_seed_count(); i++)
   {
      const rel_type_def_t *def = rel_types_seed_at(i);
      const char *sens = go_sensitivity(def->sensitivity);
      if (!sens)
      {
         fprintf(stderr, "seed row %s has sensitivity %d, which the Go port does not name\n",
                 def->rel_type, def->sensitivity);
         exit(1);
      }
      fprintf(f, "\t{RelType: \"%s\", HeadKinds: ", def->rel_type);
      write_kind_list(f, def->head_kinds, def->head_kind_count);
      fputs(", TailKinds: ", f);
      write_kind_list(f, def->tail_kinds, def->tail_kind_count);
      fprintf(f, ", Sensitivity: %s},\n", sens);
   }
   fputs("}\n", f);
   fclose(f);
}

static void write_kind_field(FILE *f, const memory_node_kind_t *kinds, int count)
{
   for (int i = 0; i < count; i++)
      fprintf(f, "%s%d", i ? ";" : "", (int)kinds[i]);
}

static void write_tsv(const char *path)
{
   FILE *f = fopen(path, "w");
   if (!f)
   {
      perror(path);
      exit(1);
   }
   for (int i = 0; i < rel_types_seed_count(); i++)
   {
      const rel_type_def_t *def = rel_types_seed_at(i);
      fprintf(f, "%s\t", def->rel_type);
      write_kind_field(f, def->head_kinds, def->head_kind_count);
      fputc('\t', f);
      write_kind_field(f, def->tail_kinds, def->tail_kind_count);
      fprintf(f, "\t%d\n", (int)def->sensitivity);
   }
   fclose(f);
}

int main(int argc, char **argv)
{
   if (argc != 3)
   {
      fprintf(stderr, "usage: %s <ontology_seed.go> <ontology_seed.tsv>\n", argv[0]);
      return 2;
   }
   write_go(argv[1]);
   write_tsv(argv[2]);
   return 0;
}
