#!/usr/bin/env python3
"""Generate the thin client's method -> first-class /v1 route map from the /v1
route descriptor, so the client calls dedicated REST endpoints instead of
tunnelling through the retired generic dispatch endpoint.

Source of truth: docs/gen/v1-route-descriptor.json — the canonical extract of the
server's g_v1_routes[] table (produced by scripts/gen-v1-route-descriptor.py,
guarded by docs-gen-check). This generator was repointed off the C table onto the
descriptor as the first "flip" of the /v1 route SoT proposal
(docs/proposals/done/route-descriptor-single-source-of-truth.md): one derived
table (this CLI map) is now generated FROM the descriptor rather than by
re-parsing the registry. The emitted block is unchanged — this only moves where
the data is read from.

We emit one row per *synchronous* rh_dispatch_op route (RM_EXACT) — those
dispatch the NDJSON method twin verbatim and echo the raw dispatch response, so
the HTTP reply is byte-identical to the socket path and the client's existing
response handling is unchanged. Excluded on purpose:
  - rh_dispatch_op_async  : returns a queued run handle, not the direct result —
                            a different client contract (polled via /v1/runs/{id}).
  - bespoke handlers      : request/response may not match the NDJSON method.
  - RM_PREFIX ({id}) rows : handled by cli_v1_pathid_route_for_method.

The generated block lives inline in the thin-client TU (src/cli_v1_routes*.c),
between the @@GEN-CLI-V1-ROUTES BEGIN/END markers — there is no separate .inc.
Default: rewrite that region in place. `--stdout`: print the block (used by
scripts/check-cli-v1-routes.py, in `make lint`, to guard against drift).
Usage: scripts/gen-cli-v1-routes.py [--stdout]
"""
import glob
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DESCRIPTOR = ROOT / "docs" / "gen" / "v1-route-descriptor.json"
TARGET_GLOB = str(ROOT / "src" / "cli_v1_routes*.c")
MARK_BEGIN = "/* @@GEN-CLI-V1-ROUTES BEGIN — generated by scripts/gen-cli-v1-routes.py; DO NOT EDIT @@ */"
MARK_END = "/* @@GEN-CLI-V1-ROUTES END @@ */"
OPTIONAL_ROUTE_GUARDS = {
    "delegate.aggregate": "AIMEE_WITH_ROUNDTABLE",
    "delegate.roundtable": "AIMEE_WITH_ROUNDTABLE",
    "pipeline.advance": "AIMEE_WITH_ROUNDTABLE",
    "pipeline.cancel": "AIMEE_WITH_ROUNDTABLE",
    "pipeline.gate": "AIMEE_WITH_ROUNDTABLE",
    "pipeline.list": "AIMEE_WITH_ROUNDTABLE",
    "pipeline.resume": "AIMEE_WITH_ROUNDTABLE",
    "pipeline.start": "AIMEE_WITH_ROUNDTABLE",
    "pipeline.status": "AIMEE_WITH_ROUNDTABLE",
}


def _routes(handler):
    """(op, verb, path) for the RM_EXACT routes dispatched by `handler`, one route
    per op, sorted by op.

    An op may be reachable under more than one path when a route is renamed and
    the old spelling is kept as an alias. The descriptor is sorted by PATH, so
    "first wins" would hand the client whichever alias sorts earliest -- e.g.
    /v1/agent/list over /v1/model/list for model.list, pointing the thin client
    at the deprecated spelling and breaking it the day the alias is dropped.
    Prefer the path whose first segment matches the op's own namespace; fall back
    to first-seen when nothing matches (ops whose route is not named after them).
    """
    doc = json.loads(DESCRIPTOR.read_text(encoding="utf-8"))
    seen = {}
    for r in doc["routes"]:
        if r["match"] != "exact" or r["handler"] != handler or not r["op"]:
            continue
        op = r["op"]
        candidate = (r["verb"], r["path"])
        if op not in seen:
            seen[op] = candidate
            continue
        namespace = op.split(".", 1)[0]
        if r["path"].startswith(f"/v1/{namespace}/"):
            seen[op] = candidate
    return sorted((op, v, p) for op, (v, p) in seen.items())


def _emit(name, rows):
    out = ["static const struct",
           "{",
           "   const char *method;",
           "   const char *verb;",
           "   const char *path;",
           "} %s[] = {" % name]
    active_guard = None
    for op, verb, path in rows:
        guard = OPTIONAL_ROUTE_GUARDS.get(op)
        if guard != active_guard:
            if active_guard:
                out.append("#endif")
            if guard:
                out.append(f"#if {guard}")
            active_guard = guard
        out.append('    {"%s", "%s", "%s"},' % (op, verb, path))
    if active_guard:
        out.append("#endif")
    out.append("};")
    return out


def build_block():
    """The generated block text (between the markers, markers excluded)."""
    async_rows = _routes("rh_dispatch_op_async")
    async_ops = {op for op, _, _ in async_rows}
    sync_rows = [r for r in _routes("rh_dispatch_op") if r[0] not in async_ops]
    lines = [
        "/* Auto-generated from src/server/server_http_routes.c — DO NOT EDIT.",
        " *",
        " * method (op) -> first-class /v1 route for the thin client.",
        " *  - CLI_V1_GEN_ROUTES   : synchronous rh_dispatch_op routes; the HTTP",
        " *                          response is byte-identical to the NDJSON socket.",
        " *  - CLI_V1_ASYNC_ROUTES : rh_dispatch_op_async routes; POSTing returns a",
        " *                          run handle ({id}) the client polls at",
        " *                          GET /v1/runs/{id} until it completes.",
        " * Regenerate after changing the registry; scripts/check-cli-v1-routes.py",
        " * (make lint) guards against drift. */",
    ]
    lines += _emit("CLI_V1_GEN_ROUTES", sync_rows)
    lines.append("")
    lines += _emit("CLI_V1_ASYNC_ROUTES", async_rows)
    return "\n".join(lines), len(sync_rows), len(async_rows)


def _target_file():
    for f in sorted(glob.glob(TARGET_GLOB)):
        if MARK_BEGIN in Path(f).read_text(encoding="utf-8"):
            return Path(f)
    raise SystemExit(f"gen-cli-v1-routes: no @@GEN-CLI-V1-ROUTES markers found in {TARGET_GLOB}")


def _splice(target: Path, block: str):
    text = target.read_text(encoding="utf-8")
    pre, _, rest = text.partition(MARK_BEGIN)
    _, _, post = rest.partition(MARK_END)
    target.write_text(pre + MARK_BEGIN + "\n" + block + "\n" + MARK_END + post, encoding="utf-8")


def main():
    block, n_sync, n_async = build_block()
    if "--stdout" in sys.argv[1:]:
        sys.stdout.write(block + "\n")
        return
    target = _target_file()
    _splice(target, block)
    print(f"gen-cli-v1-routes: updated {target.name} "
          f"({n_sync} sync + {n_async} async routes)")


if __name__ == "__main__":
    main()
